Repository techlabsms/techlabs_new, pull requests merged in 2021-01, with the labels that each got.

#325 add data science track to apply page
  src/pages/apply.js
Labels: bug

#330 Chore/remove warnings
  .eslintrc
  gatsby-config.js
  package-lock.json
  package.json
  src/components/Layout/Footer.js
  src/components/language.js
  src/components/shared/dropdown.js
  src/styles/_main.scss
Labels: Config Changes

#321 Feature/locations newsletter
  package-lock.json
  src/components/program/newsletter.js
  src/intl/de.json
  src/intl/en.json
  src/pages/program/remote.js
  src/templates/location.js
Labels: enhancement
